version: '3.8'

services:
  auth-service:
    volumes:
      - ./services/auth-service:/app
    environment:
      - NODE_ENV=development

  product-service:
    volumes:
      - ./services/product-service:/app
    environment:
      - NODE_ENV=development

  order-service:
    volumes:
      - ./services/order-service:/app
    environment:
      - NODE_ENV=development

  frontend:
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
