version: "3.8"

services:
  frontend:
    image: ${CI_REGISTRY_NAME}/ecommercevuefrontend:${IMAGE_TAG}
    ports:
      - "8080:8080"
    depends_on:
      - product-service
      - auth-service
      - order-service
    networks:
      - e-commerce-network
    secrets:
      - env_production

  product-service:
    image: ${CI_REGISTRY_NAME}/ecommerceproductservice:${IMAGE_TAG}
    ports:
      - "3000:3000"
    depends_on:
      - mongodb-products
    networks:
      - e-commerce-network
    secrets:
      - env_production

  auth-service:
    image: ${CI_REGISTRY_NAME}/ecommerceauthservice:${IMAGE_TAG}
    ports:
      - "3001:3001"
    depends_on:
      - mongodb-auth
    networks:
      - e-commerce-network
    secrets:
      - env_production

  order-service:
    image: ${CI_REGISTRY_NAME}/ecommerceorderservice:${IMAGE_TAG}
    ports:
      - "3002:3002"
    depends_on:
      - mongodb-orders
      - product-service
    networks:
      - e-commerce-network
    secrets:
      - env_production

  mongodb-auth:
    image: mongo:4.4
    ports:
      - "27018:27017"
    volumes:
      - mongodb_auth_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=auth
    networks:
      - e-commerce-network

  mongodb-products:
    image: mongo:4.4
    ports:
      - "27019:27017"
    volumes:
      - mongodb_products_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ecommerce
    networks:
      - e-commerce-network

  mongodb-orders:
    image: mongo:4.4
    ports:
      - "27020:27017"
    volumes:
      - mongodb_orders_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=orders
    networks:
      - e-commerce-network

volumes:
  mongodb_auth_data:
  mongodb_products_data:
  mongodb_orders_data:

networks:
  e-commerce-network:
    driver: overlay

secrets:
  env_production:
    external: true
