version: "3.8"

services:
  frontend:
    image: kaliwarsteen/ecommercevuefrontend:latest
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - VITE_PRODUCT_SERVICE_URL=http://product-service:3000
      - VITE_AUTH_SERVICE_URL=http://auth-service:3001
      - VITE_ORDER_SERVICE_URL=http://order-service:3002
    depends_on:
      - product-service
      - auth-service
      - order-service
    networks:
      - e-commerce-network

  product-service:
    image: kaliwarsteen/ecommervueproduct-service:latest
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb-products:27017/ecommerce
      - NODE_ENV=production
      - JWT_SECRET=efrei_super_pass
    depends_on:
      - mongodb-products
    networks:
      - e-commerce-network

  auth-service:
    image: kaliwarsteen/ecommervueauth-service:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb-auth:27017/auth
      - JWT_SECRET=efrei_super_pass
    depends_on:
      - mongodb-auth
    networks:
      - e-commerce-network

  order-service:
    image: kaliwarsteen/ecommervueorder-service:latest
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb-orders:27017/orders
      - JWT_SECRET=efrei_super_pass
      - VITE_PRODUCT_SERVICE_URL=http://product-service:3000
    depends_on:
      - mongodb-orders
      - product-service
    networks:
      - e-commerce-network

  mongodb-auth:
    image: mongo:4.4
    ports:
      - "27018:27017"
    volumes:
      - mongodb_auth_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=auth
    networks:
      - e-commerce-network

  mongodb-products:
    image: mongo:4.4
    ports:
      - "27019:27017"
    volumes:
      - mongodb_products_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ecommerce
    networks:
      - e-commerce-network

  mongodb-orders:
    image: mongo:4.4
    ports:
      - "27020:27017"
    volumes:
      - mongodb_orders_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=orders
    networks:
      - e-commerce-network

volumes:
  mongodb_auth_data:
  mongodb_products_data:
  mongodb_orders_data:

networks:
  e-commerce-network:
    driver: overlay
