name: Docker Build CI

on:
  push:
    branches: ["develop", "feature/cicd"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Build Frontend
        run: ./frontend/build-front.yml

  build_auth:
    runs-on: ubuntu-latest
    steps:
      - name: Build Auth Service
        run: ./services/auth-service/build-auth.yml

  build_product:
    runs-on: ubuntu-latest
    steps:
      - name: Build Product Service
        run: ./services/product-service/build-product.yml

  build_order:
    runs-on: ubuntu-latest
    steps:
      - name: Build Order Service
        run: ./services/order-service/build-order.yml
